//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPHSe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLiPhatHanhSachv5Entities : DbContext
    {
        public QuanLiPhatHanhSachv5Entities()
            : base("name=QuanLiPhatHanhSachv5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTPN> CTPNs { get; set; }
        public virtual DbSet<CTPTTDAILI> CTPTTDAILIs { get; set; }
        public virtual DbSet<CTPTTNXB> CTPTTNXBs { get; set; }
        public virtual DbSet<CTPX> CTPXes { get; set; }
        public virtual DbSet<DAILY> DAILies { get; set; }
        public virtual DbSet<HANGSO> HANGSOes { get; set; }
        public virtual DbSet<NXB> NXBs { get; set; }
        public virtual DbSet<PHIEUNHAP> PHIEUNHAPs { get; set; }
        public virtual DbSet<PHIEUXUAT> PHIEUXUATs { get; set; }
        public virtual DbSet<PTTDAILI> PTTDAILIs { get; set; }
        public virtual DbSet<PTTNXB> PTTNXBs { get; set; }
        public virtual DbSet<SACH> SACHes { get; set; }
        public virtual DbSet<TONKHO> TONKHOes { get; set; }
    }
}
