//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPHSe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTTDAILI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PTTDAILI()
        {
            this.CTPTTDAILIs = new HashSet<CTPTTDAILI>();
        }
    
        public int MPTTDAILI { get; set; }
        public Nullable<int> MADL { get; set; }
        public Nullable<System.DateTime> NGAYTT { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPTTDAILI> CTPTTDAILIs { get; set; }
        public virtual DAILY DAILY { get; set; }
    }
}
